services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend  # Ensure this matches the actual filename
    ports:
      - "3000:3000"
    container_name: frontend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend  # Ensure this matches the actual filename
    ports:
      - "5000:5000"
    container_name: backend
    restart: always