apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: icr.io/cloud-native-app/backend-app:1.0  # Use your backend image
        ports:
        - containerPort: 5000
